class CreateContents < ActiveRecord::Migration
  def self.up
    create_table :contents do |t|
      t.string :path
      t.integer :account_id
      t.string :title
      t.string :subtitle
      t.text :body
      t.string :status
      t.timestamps
    end
    Content.create(
      :path => '/', :title => 'Lorem Ipsum',
      :body => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mauris diam, vulputate ac vulputate non, iaculis ut dui. Aliquam consequat posuere tincidunt. Nunc tincidunt varius velit eu egestas. Ut sagittis nulla ac arcu fringilla vitae congue est tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus id purus in eros adipiscing lacinia. Morbi sed justo dui, viverra pretium nunc. Morbi tristique leo in urna lacinia ac gravida eros tincidunt. Vivamus lobortis facilisis elit in tristique. Vivamus laoreet euismod dui quis iaculis.</p>
<p>This is default text generated by the cms project template, you probably want to start by <a href="/admin/contens/edit/1">editing this</a>.</p>
'
    )

  end

  def self.down
    drop_table :contents
  end
end
